# Generated by Django 4.2.3 on 2023-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_history_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sam',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
